name: tests_js
on: [push]

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependeciens
        run: npm install
      - name: Run tests
        run: npm test


  deploy:
    needs: test
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Deploying to production..."
